#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "atuin"
name = "Atuin"
description.en = "Self-hosted Atuin for syncing and backing up encrypted shell history across devices"
description.fr = "Atuin, pour synchroniser et sauvegarder votre historique de shell chiffré entre vos appareils."

version = "18.20.1~ynh1"
maintainers = ["ximikos"]

[upstream]
license = "MIT"
website = "https://atuin.sh"
admindoc = "https://docs.atuin.sh/cli/self-hosting/server-setup/"
userdoc = "https://docs.atuin.sh/cli/"
code = "https://github.com/atuinsh/atuin"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "500M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/atuin"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/atuinsh/atuin/releases/download/v18.20.1/atuin-server-x86_64-unknown-linux-musl.tar.gz"
    amd64.sha256 = "6e216ffd06ec0e49ca60b0e4ded9c8c71fa53daee271d4af0ae43b91a9df256b"
    arm64.url = "https://github.com/atuinsh/atuin/releases/download/v18.20.1/atuin-server-aarch64-unknown-linux-musl.tar.gz"
    arm64.sha256 = "1e01c4b05f1b2892c0e6073674cf92cc13dac65367590e661822a67e18c739e7"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^atuin-server-x86_64-unknown-linux-musl\\.tar\\.gz$"
    autoupdate.asset.arm64 = "^atuin-server-aarch64-unknown-linux-musl\\.tar\\.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false

    [resources.ports]
