#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "atuin"
name = "Atuin"
description.en = "Self-hosted Atuin for syncing and backing up encrypted shell history across devices"
description.fr = "Atuin, pour synchroniser et sauvegarder votre historique de shell chiffré entre vos appareils."

version = "18.12.0~ynh1"

maintainers = ["ximikos"]

[upstream]
license = "MIT"
website = "https://atuin.sh"
admindoc = "https://docs.atuin.sh/cli/self-hosting/server-setup/"
userdoc = "https://docs.atuin.sh/cli/"
code = "https://github.com/atuinsh/atuin"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "500M"
ram.build = "50M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/atuin"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/atuinsh/atuin/releases/download/v18.12.0/atuin-x86_64-unknown-linux-gnu.tar.gz"
    amd64.sha256 = "4aa6cef8da2c79489d3f7c6f76cb2f160903ceb86cd60c6456af8aa782274a96"
    arm64.url = "https://github.com/atuinsh/atuin/releases/download/v18.12.0/atuin-aarch64-unknown-linux-gnu.tar.gz"
    arm64.sha256 = "f7d9bfdd7326cb4b2c07f9ee998b5f7cabedf75f00e68bddf8ea16e283348073"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^atuin-x86_64-unknown-linux-gnu\\.tar\\.gz$"
    autoupdate.asset.arm64 = "^atuin-aarch64-unknown-linux-gnu\\.tar\\.gz$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.show_tile = false

    [resources.ports]
